### ISSUE TITLE
Chamadas infinitas para www.google.com

### ISSUE THREAD

**Issue by VdBarros** [ipirangad3v/kmule#25]
Ao adicionar a lib no projeto, utilizando o network inspector notei que é feita uma chamada para www.google.com a cada segundo, isso é muito prejudicial para a performance do app e também utilização de dados do usuário final.

Ao retirar a lib o problema para de acontecer.

Estou utilizando as seguintes versões do ktor:
ktorClientAndroid = "2.3.2"
ktorClientCore = "2.3.7" 

<img width="1371" alt="kmule" src="https://github.com/ipirangad3v/kmule/assets/52058053/9ada7e47-26c9-4d3a-b6a6-5ffef95900eb">
<img width="545" alt="kmule1" src="https://github.com/ipirangad3v/kmule/assets/52058053/4be4eba2-1143-49e0-bf94-b00ed1bce1c4">

**Comment by ipirangad3v** [comment]
Olá. corrigi isso na versão 0.0.5. Infelizmente estou com problemas para acessar minha conta para publicar a versão. Sugiro usar a versão 0.0.3 como alternativa

**Comment by ipirangad3v** [comment]
Olá novamente, Consegui subir a versão 0.0.5. Por favor atualize, o problema está corrigido. Obrigado pelo report.
